package vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 자유게시판 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FreeReply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글 번호. */
	private Integer frrno;

	/** 댓글 내용. */
	private String frrcontent;

	/** 댓글 작성일. */
	private Date frrdate;

	/** 회원정보. */
	private Member member;

	/** 자유게시판. */
	private Free free;

	/**
	 * 생성자.
	 */
	public FreeReply() {
	}

	/**
	 * 댓글 번호을 설정합니다..
	 * 
	 * @param frrno
	 *            댓글 번호
	 */
	public void setFrrno(Integer frrno) {
		this.frrno = frrno;
	}

	/**
	 * 댓글 번호을 가져옵니다..
	 * 
	 * @return 댓글 번호
	 */
	public Integer getFrrno() {
		return this.frrno;
	}

	/**
	 * 댓글 내용을 설정합니다..
	 * 
	 * @param frrcontent
	 *            댓글 내용
	 */
	public void setFrrcontent(String frrcontent) {
		this.frrcontent = frrcontent;
	}

	/**
	 * 댓글 내용을 가져옵니다..
	 * 
	 * @return 댓글 내용
	 */
	public String getFrrcontent() {
		return this.frrcontent;
	}

	/**
	 * 댓글 작성일을 설정합니다..
	 * 
	 * @param frrdate
	 *            댓글 작성일
	 */
	public void setFrrdate(Date frrdate) {
		this.frrdate = frrdate;
	}

	/**
	 * 댓글 작성일을 가져옵니다..
	 * 
	 * @return 댓글 작성일
	 */
	public Date getFrrdate() {
		return this.frrdate;
	}

	/**
	 * 회원정보을 설정합니다..
	 * 
	 * @param member
	 *            회원정보
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 회원정보을 가져옵니다..
	 * 
	 * @return 회원정보
	 */
	public Member getMember() {
		return this.member;
	}

	/**
	 * 자유게시판을 설정합니다..
	 * 
	 * @param free
	 *            자유게시판
	 */
	public void setFree(Free free) {
		this.free = free;
	}

	/**
	 * 자유게시판을 가져옵니다..
	 * 
	 * @return 자유게시판
	 */
	public Free getFree() {
		return this.free;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((frrno == null) ? 0 : frrno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FreeReply other = (FreeReply) obj;
		if (frrno == null) {
			if (other.frrno != null) {
				return false;
			}
		} else if (!frrno.equals(other.frrno)) {
			return false;
		}
		return true;
	}

}
