package vo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 회원정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Member implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 회원번호. */
	private Integer mno;

	/** 아이디. */
	private String mid;

	/** 비밀번호. */
	private String mpw;

	/** 닉네임. */
	private String mnicknm;

	/** 이름. */
	private String mname;

	/** 생년월일. */
	private Integer mbirth;

	/** 연락처. */
	private String mphone;

	/** 성별. */
	private String mgender;

	/** 이메일. */
	private String memail;

	/** 회원가입일. */
	private Date mrdate;

	/** 출석체크 게시판 목록. */
	private Set<Attendcheck> attendcheckSet;

	/** 출석체크 댓글 목록. */
	private Set<AttendcheckReply> attendcheckReplySet;

	/** 자유게시판 목록. */
	private Set<Free> freeSet;

	/** 자유게시판 댓글 목록. */
	private Set<FreeReply> freeReplySet;

	/** 장비게시판 목록. */
	private Set<Gear> gearSet;

	/** 장비게시판 댓글 목록. */
	private Set<GearReply> gearReplySet;

	/** 공지사항 게시글 목록. */
	private Set<Notice> noticeSet;

	/** 공지사항 댓글 목록. */
	private Set<NoticeReply> noticeReplySet;

	/** 질문게시판 목록. */
	private Set<Qna> qnaSet;

	/** 질문게시판 댓글 목록. */
	private Set<QnaReply> qnaReplySet;

	/** 지역 게시글 목록. */
	private Set<Zone> zoneSet;

	/** 지역 댓글 목록. */
	private Set<ZoneReply> zoneReplySet;

	/**
	 * 생성자.
	 */
	public Member() {
		this.qnaSet = new HashSet<Qna>();
		this.qnaReplySet = new HashSet<QnaReply>();
		this.attendcheckSet = new HashSet<Attendcheck>();
		this.attendcheckReplySet = new HashSet<AttendcheckReply>();
		this.freeSet = new HashSet<Free>();
		this.freeReplySet = new HashSet<FreeReply>();
		this.gearSet = new HashSet<Gear>();
		this.gearReplySet = new HashSet<GearReply>();
		this.noticeSet = new HashSet<Notice>();
		this.noticeReplySet = new HashSet<NoticeReply>();
		this.zoneSet = new HashSet<Zone>();
		this.zoneReplySet = new HashSet<ZoneReply>();
	}

	/**
	 * 회원번호을 설정합니다..
	 * 
	 * @param mno
	 *            회원번호
	 */
	public void setMno(Integer mno) {
		this.mno = mno;
	}

	/**
	 * 회원번호을 가져옵니다..
	 * 
	 * @return 회원번호
	 */
	public Integer getMno() {
		return this.mno;
	}

	/**
	 * 아이디을 설정합니다..
	 * 
	 * @param mid
	 *            아이디
	 */
	public void setMid(String mid) {
		this.mid = mid;
	}

	/**
	 * 아이디을 가져옵니다..
	 * 
	 * @return 아이디
	 */
	public String getMid() {
		return this.mid;
	}

	/**
	 * 비밀번호을 설정합니다..
	 * 
	 * @param mpw
	 *            비밀번호
	 */
	public void setMpw(String mpw) {
		this.mpw = mpw;
	}

	/**
	 * 비밀번호을 가져옵니다..
	 * 
	 * @return 비밀번호
	 */
	public String getMpw() {
		return this.mpw;
	}

	/**
	 * 닉네임을 설정합니다..
	 * 
	 * @param mnicknm
	 *            닉네임
	 */
	public void setMnicknm(String mnicknm) {
		this.mnicknm = mnicknm;
	}

	/**
	 * 닉네임을 가져옵니다..
	 * 
	 * @return 닉네임
	 */
	public String getMnicknm() {
		return this.mnicknm;
	}

	/**
	 * 이름을 설정합니다..
	 * 
	 * @param mname
	 *            이름
	 */
	public void setMname(String mname) {
		this.mname = mname;
	}

	/**
	 * 이름을 가져옵니다..
	 * 
	 * @return 이름
	 */
	public String getMname() {
		return this.mname;
	}

	/**
	 * 생년월일을 설정합니다..
	 * 
	 * @param mbirth
	 *            생년월일
	 */
	public void setMbirth(Integer mbirth) {
		this.mbirth = mbirth;
	}

	/**
	 * 생년월일을 가져옵니다..
	 * 
	 * @return 생년월일
	 */
	public Integer getMbirth() {
		return this.mbirth;
	}

	/**
	 * 연락처을 설정합니다..
	 * 
	 * @param mphone
	 *            연락처
	 */
	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	/**
	 * 연락처을 가져옵니다..
	 * 
	 * @return 연락처
	 */
	public String getMphone() {
		return this.mphone;
	}

	/**
	 * 성별을 설정합니다..
	 * 
	 * @param mgender
	 *            성별
	 */
	public void setMgender(String mgender) {
		this.mgender = mgender;
	}

	/**
	 * 성별을 가져옵니다..
	 * 
	 * @return 성별
	 */
	public String getMgender() {
		return this.mgender;
	}

	/**
	 * 이메일을 설정합니다..
	 * 
	 * @param memail
	 *            이메일
	 */
	public void setMemail(String memail) {
		this.memail = memail;
	}

	/**
	 * 이메일을 가져옵니다..
	 * 
	 * @return 이메일
	 */
	public String getMemail() {
		return this.memail;
	}

	/**
	 * 회원가입일을 설정합니다..
	 * 
	 * @param mrdate
	 *            회원가입일
	 */
	public void setMrdate(Date mrdate) {
		this.mrdate = mrdate;
	}

	/**
	 * 회원가입일을 가져옵니다..
	 * 
	 * @return 회원가입일
	 */
	public Date getMrdate() {
		return this.mrdate;
	}

	/**
	 * 출석체크 게시판 목록을 설정합니다..
	 * 
	 * @param attendcheckSet
	 *            출석체크 게시판 목록
	 */
	public void setAttendcheckSet(Set<Attendcheck> attendcheckSet) {
		this.attendcheckSet = attendcheckSet;
	}

	/**
	 * 출석체크 게시판를 추가합니다..
	 * 
	 * @param attendcheck
	 *            출석체크 게시판
	 */
	public void addAttendcheck(Attendcheck attendcheck) {
		this.attendcheckSet.add(attendcheck);
	}

	/**
	 * 출석체크 게시판 목록을 가져옵니다..
	 * 
	 * @return 출석체크 게시판 목록
	 */
	public Set<Attendcheck> getAttendcheckSet() {
		return this.attendcheckSet;
	}

	/**
	 * 출석체크 댓글 목록을 설정합니다..
	 * 
	 * @param attendcheckReplySet
	 *            출석체크 댓글 목록
	 */
	public void setAttendcheckReplySet(Set<AttendcheckReply> attendcheckReplySet) {
		this.attendcheckReplySet = attendcheckReplySet;
	}

	/**
	 * 출석체크 댓글를 추가합니다..
	 * 
	 * @param attendcheckReply
	 *            출석체크 댓글
	 */
	public void addAttendcheckReply(AttendcheckReply attendcheckReply) {
		this.attendcheckReplySet.add(attendcheckReply);
	}

	/**
	 * 출석체크 댓글 목록을 가져옵니다..
	 * 
	 * @return 출석체크 댓글 목록
	 */
	public Set<AttendcheckReply> getAttendcheckReplySet() {
		return this.attendcheckReplySet;
	}

	/**
	 * 자유게시판 목록을 설정합니다..
	 * 
	 * @param freeSet
	 *            자유게시판 목록
	 */
	public void setFreeSet(Set<Free> freeSet) {
		this.freeSet = freeSet;
	}

	/**
	 * 자유게시판를 추가합니다..
	 * 
	 * @param free
	 *            자유게시판
	 */
	public void addFree(Free free) {
		this.freeSet.add(free);
	}

	/**
	 * 자유게시판 목록을 가져옵니다..
	 * 
	 * @return 자유게시판 목록
	 */
	public Set<Free> getFreeSet() {
		return this.freeSet;
	}

	/**
	 * 자유게시판 댓글 목록을 설정합니다..
	 * 
	 * @param freeReplySet
	 *            자유게시판 댓글 목록
	 */
	public void setFreeReplySet(Set<FreeReply> freeReplySet) {
		this.freeReplySet = freeReplySet;
	}

	/**
	 * 자유게시판 댓글를 추가합니다..
	 * 
	 * @param freeReply
	 *            자유게시판 댓글
	 */
	public void addFreeReply(FreeReply freeReply) {
		this.freeReplySet.add(freeReply);
	}

	/**
	 * 자유게시판 댓글 목록을 가져옵니다..
	 * 
	 * @return 자유게시판 댓글 목록
	 */
	public Set<FreeReply> getFreeReplySet() {
		return this.freeReplySet;
	}

	/**
	 * 장비게시판 목록을 설정합니다..
	 * 
	 * @param gearSet
	 *            장비게시판 목록
	 */
	public void setGearSet(Set<Gear> gearSet) {
		this.gearSet = gearSet;
	}

	/**
	 * 장비게시판를 추가합니다..
	 * 
	 * @param gear
	 *            장비게시판
	 */
	public void addGear(Gear gear) {
		this.gearSet.add(gear);
	}

	/**
	 * 장비게시판 목록을 가져옵니다..
	 * 
	 * @return 장비게시판 목록
	 */
	public Set<Gear> getGearSet() {
		return this.gearSet;
	}

	/**
	 * 장비게시판 댓글 목록을 설정합니다..
	 * 
	 * @param gearReplySet
	 *            장비게시판 댓글 목록
	 */
	public void setGearReplySet(Set<GearReply> gearReplySet) {
		this.gearReplySet = gearReplySet;
	}

	/**
	 * 장비게시판 댓글를 추가합니다..
	 * 
	 * @param gearReply
	 *            장비게시판 댓글
	 */
	public void addGearReply(GearReply gearReply) {
		this.gearReplySet.add(gearReply);
	}

	/**
	 * 장비게시판 댓글 목록을 가져옵니다..
	 * 
	 * @return 장비게시판 댓글 목록
	 */
	public Set<GearReply> getGearReplySet() {
		return this.gearReplySet;
	}

	/**
	 * 공지사항 게시글 목록을 설정합니다..
	 * 
	 * @param noticeSet
	 *            공지사항 게시글 목록
	 */
	public void setNoticeSet(Set<Notice> noticeSet) {
		this.noticeSet = noticeSet;
	}

	/**
	 * 공지사항 게시글를 추가합니다..
	 * 
	 * @param notice
	 *            공지사항 게시글
	 */
	public void addNotice(Notice notice) {
		this.noticeSet.add(notice);
	}

	/**
	 * 공지사항 게시글 목록을 가져옵니다..
	 * 
	 * @return 공지사항 게시글 목록
	 */
	public Set<Notice> getNoticeSet() {
		return this.noticeSet;
	}

	/**
	 * 공지사항 댓글 목록을 설정합니다..
	 * 
	 * @param noticeReplySet
	 *            공지사항 댓글 목록
	 */
	public void setNoticeReplySet(Set<NoticeReply> noticeReplySet) {
		this.noticeReplySet = noticeReplySet;
	}

	/**
	 * 공지사항 댓글를 추가합니다..
	 * 
	 * @param noticeReply
	 *            공지사항 댓글
	 */
	public void addNoticeReply(NoticeReply noticeReply) {
		this.noticeReplySet.add(noticeReply);
	}

	/**
	 * 공지사항 댓글 목록을 가져옵니다..
	 * 
	 * @return 공지사항 댓글 목록
	 */
	public Set<NoticeReply> getNoticeReplySet() {
		return this.noticeReplySet;
	}

	/**
	 * 질문게시판 목록을 설정합니다..
	 * 
	 * @param qnaSet
	 *            질문게시판 목록
	 */
	public void setQnaSet(Set<Qna> qnaSet) {
		this.qnaSet = qnaSet;
	}

	/**
	 * 질문게시판를 추가합니다..
	 * 
	 * @param qna
	 *            질문게시판
	 */
	public void addQna(Qna qna) {
		this.qnaSet.add(qna);
	}

	/**
	 * 질문게시판 목록을 가져옵니다..
	 * 
	 * @return 질문게시판 목록
	 */
	public Set<Qna> getQnaSet() {
		return this.qnaSet;
	}

	/**
	 * 질문게시판 댓글 목록을 설정합니다..
	 * 
	 * @param qnaReplySet
	 *            질문게시판 댓글 목록
	 */
	public void setQnaReplySet(Set<QnaReply> qnaReplySet) {
		this.qnaReplySet = qnaReplySet;
	}

	/**
	 * 질문게시판 댓글를 추가합니다..
	 * 
	 * @param qnaReply
	 *            질문게시판 댓글
	 */
	public void addQnaReply(QnaReply qnaReply) {
		this.qnaReplySet.add(qnaReply);
	}

	/**
	 * 질문게시판 댓글 목록을 가져옵니다..
	 * 
	 * @return 질문게시판 댓글 목록
	 */
	public Set<QnaReply> getQnaReplySet() {
		return this.qnaReplySet;
	}

	/**
	 * 지역 게시글 목록을 설정합니다..
	 * 
	 * @param zoneSet
	 *            지역 게시글 목록
	 */
	public void setZoneSet(Set<Zone> zoneSet) {
		this.zoneSet = zoneSet;
	}

	/**
	 * 지역 게시글를 추가합니다..
	 * 
	 * @param zone
	 *            지역 게시글
	 */
	public void addZone(Zone zone) {
		this.zoneSet.add(zone);
	}

	/**
	 * 지역 게시글 목록을 가져옵니다..
	 * 
	 * @return 지역 게시글 목록
	 */
	public Set<Zone> getZoneSet() {
		return this.zoneSet;
	}

	/**
	 * 지역 댓글 목록을 설정합니다..
	 * 
	 * @param zoneReplySet
	 *            지역 댓글 목록
	 */
	public void setZoneReplySet(Set<ZoneReply> zoneReplySet) {
		this.zoneReplySet = zoneReplySet;
	}

	/**
	 * 지역 댓글를 추가합니다..
	 * 
	 * @param zoneReply
	 *            지역 댓글
	 */
	public void addZoneReply(ZoneReply zoneReply) {
		this.zoneReplySet.add(zoneReply);
	}

	/**
	 * 지역 댓글 목록을 가져옵니다..
	 * 
	 * @return 지역 댓글 목록
	 */
	public Set<ZoneReply> getZoneReplySet() {
		return this.zoneReplySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((mno == null) ? 0 : mno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Member other = (Member) obj;
		if (mno == null) {
			if (other.mno != null) {
				return false;
			}
		} else if (!mno.equals(other.mno)) {
			return false;
		}
		return true;
	}

}
