package vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 지역 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ZoneReply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글 번호. */
	private Integer znrno;

	/**  댓글 내용. */
	private String znrcontent;

	/** 댓글 작성일. */
	private Date znrdate;

	/** 회원정보. */
	private Member member;

	/** 지역 게시글. */
	private Zone zone;

	/**
	 * 생성자.
	 */
	public ZoneReply() {
	}

	/**
	 * 댓글 번호을 설정합니다..
	 * 
	 * @param znrno
	 *            댓글 번호
	 */
	public void setZnrno(Integer znrno) {
		this.znrno = znrno;
	}

	/**
	 * 댓글 번호을 가져옵니다..
	 * 
	 * @return 댓글 번호
	 */
	public Integer getZnrno() {
		return this.znrno;
	}

	/**
	 *  댓글 내용을 설정합니다..
	 * 
	 * @param znrcontent
	 *             댓글 내용
	 */
	public void setZnrcontent(String znrcontent) {
		this.znrcontent = znrcontent;
	}

	/**
	 *  댓글 내용을 가져옵니다..
	 * 
	 * @return  댓글 내용
	 */
	public String getZnrcontent() {
		return this.znrcontent;
	}

	/**
	 * 댓글 작성일을 설정합니다..
	 * 
	 * @param znrdate
	 *            댓글 작성일
	 */
	public void setZnrdate(Date znrdate) {
		this.znrdate = znrdate;
	}

	/**
	 * 댓글 작성일을 가져옵니다..
	 * 
	 * @return 댓글 작성일
	 */
	public Date getZnrdate() {
		return this.znrdate;
	}

	/**
	 * 회원정보을 설정합니다..
	 * 
	 * @param member
	 *            회원정보
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 회원정보을 가져옵니다..
	 * 
	 * @return 회원정보
	 */
	public Member getMember() {
		return this.member;
	}

	/**
	 * 지역 게시글을 설정합니다..
	 * 
	 * @param zone
	 *            지역 게시글
	 */
	public void setZone(Zone zone) {
		this.zone = zone;
	}

	/**
	 * 지역 게시글을 가져옵니다..
	 * 
	 * @return 지역 게시글
	 */
	public Zone getZone() {
		return this.zone;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((znrno == null) ? 0 : znrno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ZoneReply other = (ZoneReply) obj;
		if (znrno == null) {
			if (other.znrno != null) {
				return false;
			}
		} else if (!znrno.equals(other.znrno)) {
			return false;
		}
		return true;
	}

}
