package vo;

import java.io.Serializable;
import java.util.Date;

/**
 * 지역 첨부파일 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ZoneUploadfile implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 첨부파일 번호. */
	private Integer znfno;

	/** 첨부파일 실제이름. */
	private String znfrealnm;

	/** 첨부파일 원본이름. */
	private String znforiginnm;

	/** 첨부파일 등록일. */
	private Date znfrdate;

	/** 지역 게시글. */
	private Zone zone;

	/**
	 * 생성자.
	 */
	public ZoneUploadfile() {
	}

	/**
	 * 첨부파일 번호을 설정합니다..
	 * 
	 * @param znfno
	 *            첨부파일 번호
	 */
	public void setZnfno(Integer znfno) {
		this.znfno = znfno;
	}

	/**
	 * 첨부파일 번호을 가져옵니다..
	 * 
	 * @return 첨부파일 번호
	 */
	public Integer getZnfno() {
		return this.znfno;
	}

	/**
	 * 첨부파일 실제이름을 설정합니다..
	 * 
	 * @param znfrealnm
	 *            첨부파일 실제이름
	 */
	public void setZnfrealnm(String znfrealnm) {
		this.znfrealnm = znfrealnm;
	}

	/**
	 * 첨부파일 실제이름을 가져옵니다..
	 * 
	 * @return 첨부파일 실제이름
	 */
	public String getZnfrealnm() {
		return this.znfrealnm;
	}

	/**
	 * 첨부파일 원본이름을 설정합니다..
	 * 
	 * @param znforiginnm
	 *            첨부파일 원본이름
	 */
	public void setZnforiginnm(String znforiginnm) {
		this.znforiginnm = znforiginnm;
	}

	/**
	 * 첨부파일 원본이름을 가져옵니다..
	 * 
	 * @return 첨부파일 원본이름
	 */
	public String getZnforiginnm() {
		return this.znforiginnm;
	}

	/**
	 * 첨부파일 등록일을 설정합니다..
	 * 
	 * @param znfrdate
	 *            첨부파일 등록일
	 */
	public void setZnfrdate(Date znfrdate) {
		this.znfrdate = znfrdate;
	}

	/**
	 * 첨부파일 등록일을 가져옵니다..
	 * 
	 * @return 첨부파일 등록일
	 */
	public Date getZnfrdate() {
		return this.znfrdate;
	}

	/**
	 * 지역 게시글을 설정합니다..
	 * 
	 * @param zone
	 *            지역 게시글
	 */
	public void setZone(Zone zone) {
		this.zone = zone;
	}

	/**
	 * 지역 게시글을 가져옵니다..
	 * 
	 * @return 지역 게시글
	 */
	public Zone getZone() {
		return this.zone;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((znfno == null) ? 0 : znfno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		ZoneUploadfile other = (ZoneUploadfile) obj;
		if (znfno == null) {
			if (other.znfno != null) {
				return false;
			}
		} else if (!znfno.equals(other.znfno)) {
			return false;
		}
		return true;
	}

}
