package tableVo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 출석체크 게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Attendcheck implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글 번호. */
	private Integer chno;

	/** 게시글 제목. */
	private String chtitle;

	/** 게시글 내용. */
	private String chcontent;

	/** 게시글 등록일. */
	private Date chrdate;

	/** 게시글 조회수. */
	private Integer chhit;

	/** 회원정보. */
	private Member member;

	/** 출석체크 댓글 목록. */
	private Set<AttendcheckReply> attendcheckReplySet;

	/**
	 * 생성자.
	 */
	public Attendcheck() {
		this.attendcheckReplySet = new HashSet<AttendcheckReply>();
	}

	/**
	 * 게시글 번호을 설정합니다..
	 * 
	 * @param chno
	 *            게시글 번호
	 */
	public void setChno(Integer chno) {
		this.chno = chno;
	}

	/**
	 * 게시글 번호을 가져옵니다..
	 * 
	 * @return 게시글 번호
	 */
	public Integer getChno() {
		return this.chno;
	}

	/**
	 * 게시글 제목을 설정합니다..
	 * 
	 * @param chtitle
	 *            게시글 제목
	 */
	public void setChtitle(String chtitle) {
		this.chtitle = chtitle;
	}

	/**
	 * 게시글 제목을 가져옵니다..
	 * 
	 * @return 게시글 제목
	 */
	public String getChtitle() {
		return this.chtitle;
	}

	/**
	 * 게시글 내용을 설정합니다..
	 * 
	 * @param chcontent
	 *            게시글 내용
	 */
	public void setChcontent(String chcontent) {
		this.chcontent = chcontent;
	}

	/**
	 * 게시글 내용을 가져옵니다..
	 * 
	 * @return 게시글 내용
	 */
	public String getChcontent() {
		return this.chcontent;
	}

	/**
	 * 게시글 등록일을 설정합니다..
	 * 
	 * @param chrdate
	 *            게시글 등록일
	 */
	public void setChrdate(Date chrdate) {
		this.chrdate = chrdate;
	}

	/**
	 * 게시글 등록일을 가져옵니다..
	 * 
	 * @return 게시글 등록일
	 */
	public Date getChrdate() {
		return this.chrdate;
	}

	/**
	 * 게시글 조회수을 설정합니다..
	 * 
	 * @param chhit
	 *            게시글 조회수
	 */
	public void setChhit(Integer chhit) {
		this.chhit = chhit;
	}

	/**
	 * 게시글 조회수을 가져옵니다..
	 * 
	 * @return 게시글 조회수
	 */
	public Integer getChhit() {
		return this.chhit;
	}

	/**
	 * 회원정보을 설정합니다..
	 * 
	 * @param member
	 *            회원정보
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 회원정보을 가져옵니다..
	 * 
	 * @return 회원정보
	 */
	public Member getMember() {
		return this.member;
	}

	/**
	 * 출석체크 댓글 목록을 설정합니다..
	 * 
	 * @param attendcheckReplySet
	 *            출석체크 댓글 목록
	 */
	public void setAttendcheckReplySet(Set<AttendcheckReply> attendcheckReplySet) {
		this.attendcheckReplySet = attendcheckReplySet;
	}

	/**
	 * 출석체크 댓글를 추가합니다..
	 * 
	 * @param attendcheckReply
	 *            출석체크 댓글
	 */
	public void addAttendcheckReply(AttendcheckReply attendcheckReply) {
		this.attendcheckReplySet.add(attendcheckReply);
	}

	/**
	 * 출석체크 댓글 목록을 가져옵니다..
	 * 
	 * @return 출석체크 댓글 목록
	 */
	public Set<AttendcheckReply> getAttendcheckReplySet() {
		return this.attendcheckReplySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((chno == null) ? 0 : chno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Attendcheck other = (Attendcheck) obj;
		if (chno == null) {
			if (other.chno != null) {
				return false;
			}
		} else if (!chno.equals(other.chno)) {
			return false;
		}
		return true;
	}

}
