package tableVo;

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * 자유게시판 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Free implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 게시글 번호. */
	private Integer frno;

	/** 게시글 제목. */
	private String frtitle;

	/** 게시글 내용. */
	private String frcontent;

	/** 게시글 등록일. */
	private Date frdate;

	/** 게시글 조회수. */
	private Integer frhit;

	/** 회원정보. */
	private Member member;

	/** 자유게시판 첨부파일 목록. */
	private Set<FreeFile> freeFileSet;

	/** 자유게시판 댓글 목록. */
	private Set<FreeReply> freeReplySet;

	/**
	 * 생성자.
	 */
	public Free() {
		this.freeFileSet = new HashSet<FreeFile>();
		this.freeReplySet = new HashSet<FreeReply>();
	}

	/**
	 * 게시글 번호을 설정합니다..
	 * 
	 * @param frno
	 *            게시글 번호
	 */
	public void setFrno(Integer frno) {
		this.frno = frno;
	}

	/**
	 * 게시글 번호을 가져옵니다..
	 * 
	 * @return 게시글 번호
	 */
	public Integer getFrno() {
		return this.frno;
	}

	/**
	 * 게시글 제목을 설정합니다..
	 * 
	 * @param frtitle
	 *            게시글 제목
	 */
	public void setFrtitle(String frtitle) {
		this.frtitle = frtitle;
	}

	/**
	 * 게시글 제목을 가져옵니다..
	 * 
	 * @return 게시글 제목
	 */
	public String getFrtitle() {
		return this.frtitle;
	}

	/**
	 * 게시글 내용을 설정합니다..
	 * 
	 * @param frcontent
	 *            게시글 내용
	 */
	public void setFrcontent(String frcontent) {
		this.frcontent = frcontent;
	}

	/**
	 * 게시글 내용을 가져옵니다..
	 * 
	 * @return 게시글 내용
	 */
	public String getFrcontent() {
		return this.frcontent;
	}

	/**
	 * 게시글 등록일을 설정합니다..
	 * 
	 * @param frdate
	 *            게시글 등록일
	 */
	public void setFrdate(Date frdate) {
		this.frdate = frdate;
	}

	/**
	 * 게시글 등록일을 가져옵니다..
	 * 
	 * @return 게시글 등록일
	 */
	public Date getFrdate() {
		return this.frdate;
	}

	/**
	 * 게시글 조회수을 설정합니다..
	 * 
	 * @param frhit
	 *            게시글 조회수
	 */
	public void setFrhit(Integer frhit) {
		this.frhit = frhit;
	}

	/**
	 * 게시글 조회수을 가져옵니다..
	 * 
	 * @return 게시글 조회수
	 */
	public Integer getFrhit() {
		return this.frhit;
	}

	/**
	 * 회원정보을 설정합니다..
	 * 
	 * @param member
	 *            회원정보
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 회원정보을 가져옵니다..
	 * 
	 * @return 회원정보
	 */
	public Member getMember() {
		return this.member;
	}

	/**
	 * 자유게시판 첨부파일 목록을 설정합니다..
	 * 
	 * @param freeFileSet
	 *            자유게시판 첨부파일 목록
	 */
	public void setFreeFileSet(Set<FreeFile> freeFileSet) {
		this.freeFileSet = freeFileSet;
	}

	/**
	 * 자유게시판 첨부파일를 추가합니다..
	 * 
	 * @param freeFile
	 *            자유게시판 첨부파일
	 */
	public void addFreeFile(FreeFile freeFile) {
		this.freeFileSet.add(freeFile);
	}

	/**
	 * 자유게시판 첨부파일 목록을 가져옵니다..
	 * 
	 * @return 자유게시판 첨부파일 목록
	 */
	public Set<FreeFile> getFreeFileSet() {
		return this.freeFileSet;
	}

	/**
	 * 자유게시판 댓글 목록을 설정합니다..
	 * 
	 * @param freeReplySet
	 *            자유게시판 댓글 목록
	 */
	public void setFreeReplySet(Set<FreeReply> freeReplySet) {
		this.freeReplySet = freeReplySet;
	}

	/**
	 * 자유게시판 댓글를 추가합니다..
	 * 
	 * @param freeReply
	 *            자유게시판 댓글
	 */
	public void addFreeReply(FreeReply freeReply) {
		this.freeReplySet.add(freeReply);
	}

	/**
	 * 자유게시판 댓글 목록을 가져옵니다..
	 * 
	 * @return 자유게시판 댓글 목록
	 */
	public Set<FreeReply> getFreeReplySet() {
		return this.freeReplySet;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((frno == null) ? 0 : frno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Free other = (Free) obj;
		if (frno == null) {
			if (other.frno != null) {
				return false;
			}
		} else if (!frno.equals(other.frno)) {
			return false;
		}
		return true;
	}

}
