package tableVo;

import java.io.Serializable;
import java.util.Date;

/**
 * 자유게시판 첨부파일 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FreeFile implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 첨부파일 번호. */
	private Integer frfno;

	/** 첨부파일 실제이름. */
	private String frfrealnm;

	/** 첨부파일 원본이름. */
	private String frforignnm;

	/** 첨부파일 등록일. */
	private Date frfrdate;

	/** 자유게시판. */
	private Free free;

	/**
	 * 생성자.
	 */
	public FreeFile() {
	}

	/**
	 * 첨부파일 번호을 설정합니다..
	 * 
	 * @param frfno
	 *            첨부파일 번호
	 */
	public void setFrfno(Integer frfno) {
		this.frfno = frfno;
	}

	/**
	 * 첨부파일 번호을 가져옵니다..
	 * 
	 * @return 첨부파일 번호
	 */
	public Integer getFrfno() {
		return this.frfno;
	}

	/**
	 * 첨부파일 실제이름을 설정합니다..
	 * 
	 * @param frfrealnm
	 *            첨부파일 실제이름
	 */
	public void setFrfrealnm(String frfrealnm) {
		this.frfrealnm = frfrealnm;
	}

	/**
	 * 첨부파일 실제이름을 가져옵니다..
	 * 
	 * @return 첨부파일 실제이름
	 */
	public String getFrfrealnm() {
		return this.frfrealnm;
	}

	/**
	 * 첨부파일 원본이름을 설정합니다..
	 * 
	 * @param frforignnm
	 *            첨부파일 원본이름
	 */
	public void setFrforignnm(String frforignnm) {
		this.frforignnm = frforignnm;
	}

	/**
	 * 첨부파일 원본이름을 가져옵니다..
	 * 
	 * @return 첨부파일 원본이름
	 */
	public String getFrforignnm() {
		return this.frforignnm;
	}

	/**
	 * 첨부파일 등록일을 설정합니다..
	 * 
	 * @param frfrdate
	 *            첨부파일 등록일
	 */
	public void setFrfrdate(Date frfrdate) {
		this.frfrdate = frfrdate;
	}

	/**
	 * 첨부파일 등록일을 가져옵니다..
	 * 
	 * @return 첨부파일 등록일
	 */
	public Date getFrfrdate() {
		return this.frfrdate;
	}

	/**
	 * 자유게시판을 설정합니다..
	 * 
	 * @param free
	 *            자유게시판
	 */
	public void setFree(Free free) {
		this.free = free;
	}

	/**
	 * 자유게시판을 가져옵니다..
	 * 
	 * @return 자유게시판
	 */
	public Free getFree() {
		return this.free;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((frfno == null) ? 0 : frfno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		FreeFile other = (FreeFile) obj;
		if (frfno == null) {
			if (other.frfno != null) {
				return false;
			}
		} else if (!frfno.equals(other.frfno)) {
			return false;
		}
		return true;
	}

}
