package tableVo;

import java.io.Serializable;
import java.util.Date;

/**
 * 공지사항 첨부파일 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NoticeUploadfile implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 첨부파일 번호. */
	private Integer nofno;

	/** 첨부파일 실제이름. */
	private String nofrealnm;

	/** 첨부파일 원본이름. */
	private String noforiginnm;

	/** 첨부파일 등록일. */
	private Date nofrdate;

	/** 공지사항 게시글. */
	private Notice notice;

	/**
	 * 생성자.
	 */
	public NoticeUploadfile() {
	}

	/**
	 * 첨부파일 번호을 설정합니다..
	 * 
	 * @param nofno
	 *            첨부파일 번호
	 */
	public void setNofno(Integer nofno) {
		this.nofno = nofno;
	}

	/**
	 * 첨부파일 번호을 가져옵니다..
	 * 
	 * @return 첨부파일 번호
	 */
	public Integer getNofno() {
		return this.nofno;
	}

	/**
	 * 첨부파일 실제이름을 설정합니다..
	 * 
	 * @param nofrealnm
	 *            첨부파일 실제이름
	 */
	public void setNofrealnm(String nofrealnm) {
		this.nofrealnm = nofrealnm;
	}

	/**
	 * 첨부파일 실제이름을 가져옵니다..
	 * 
	 * @return 첨부파일 실제이름
	 */
	public String getNofrealnm() {
		return this.nofrealnm;
	}

	/**
	 * 첨부파일 원본이름을 설정합니다..
	 * 
	 * @param noforiginnm
	 *            첨부파일 원본이름
	 */
	public void setNoforiginnm(String noforiginnm) {
		this.noforiginnm = noforiginnm;
	}

	/**
	 * 첨부파일 원본이름을 가져옵니다..
	 * 
	 * @return 첨부파일 원본이름
	 */
	public String getNoforiginnm() {
		return this.noforiginnm;
	}

	/**
	 * 첨부파일 등록일을 설정합니다..
	 * 
	 * @param nofrdate
	 *            첨부파일 등록일
	 */
	public void setNofrdate(Date nofrdate) {
		this.nofrdate = nofrdate;
	}

	/**
	 * 첨부파일 등록일을 가져옵니다..
	 * 
	 * @return 첨부파일 등록일
	 */
	public Date getNofrdate() {
		return this.nofrdate;
	}

	/**
	 * 공지사항 게시글을 설정합니다..
	 * 
	 * @param notice
	 *            공지사항 게시글
	 */
	public void setNotice(Notice notice) {
		this.notice = notice;
	}

	/**
	 * 공지사항 게시글을 가져옵니다..
	 * 
	 * @return 공지사항 게시글
	 */
	public Notice getNotice() {
		return this.notice;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((nofno == null) ? 0 : nofno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NoticeUploadfile other = (NoticeUploadfile) obj;
		if (nofno == null) {
			if (other.nofno != null) {
				return false;
			}
		} else if (!nofno.equals(other.nofno)) {
			return false;
		}
		return true;
	}

}
