package tableVo;

import java.io.Serializable;
import java.util.Date;

/**
 * 질문게시판 첨부파일 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QnaFile implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 첨부파일 번호. */
	private Integer qufno;

	/** 첨부파일 실제이름. */
	private String qufrealnm;

	/** 첨부파일 원본이름. */
	private String quforiginnm;

	/** 첨부파일 등록일. */
	private Date qufrdate;

	/** 질문게시판. */
	private Qna qna;

	/**
	 * 생성자.
	 */
	public QnaFile() {
	}

	/**
	 * 첨부파일 번호을 설정합니다..
	 * 
	 * @param qufno
	 *            첨부파일 번호
	 */
	public void setQufno(Integer qufno) {
		this.qufno = qufno;
	}

	/**
	 * 첨부파일 번호을 가져옵니다..
	 * 
	 * @return 첨부파일 번호
	 */
	public Integer getQufno() {
		return this.qufno;
	}

	/**
	 * 첨부파일 실제이름을 설정합니다..
	 * 
	 * @param qufrealnm
	 *            첨부파일 실제이름
	 */
	public void setQufrealnm(String qufrealnm) {
		this.qufrealnm = qufrealnm;
	}

	/**
	 * 첨부파일 실제이름을 가져옵니다..
	 * 
	 * @return 첨부파일 실제이름
	 */
	public String getQufrealnm() {
		return this.qufrealnm;
	}

	/**
	 * 첨부파일 원본이름을 설정합니다..
	 * 
	 * @param quforiginnm
	 *            첨부파일 원본이름
	 */
	public void setQuforiginnm(String quforiginnm) {
		this.quforiginnm = quforiginnm;
	}

	/**
	 * 첨부파일 원본이름을 가져옵니다..
	 * 
	 * @return 첨부파일 원본이름
	 */
	public String getQuforiginnm() {
		return this.quforiginnm;
	}

	/**
	 * 첨부파일 등록일을 설정합니다..
	 * 
	 * @param qufrdate
	 *            첨부파일 등록일
	 */
	public void setQufrdate(Date qufrdate) {
		this.qufrdate = qufrdate;
	}

	/**
	 * 첨부파일 등록일을 가져옵니다..
	 * 
	 * @return 첨부파일 등록일
	 */
	public Date getQufrdate() {
		return this.qufrdate;
	}

	/**
	 * 질문게시판을 설정합니다..
	 * 
	 * @param qna
	 *            질문게시판
	 */
	public void setQna(Qna qna) {
		this.qna = qna;
	}

	/**
	 * 질문게시판을 가져옵니다..
	 * 
	 * @return 질문게시판
	 */
	public Qna getQna() {
		return this.qna;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qufno == null) ? 0 : qufno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		QnaFile other = (QnaFile) obj;
		if (qufno == null) {
			if (other.qufno != null) {
				return false;
			}
		} else if (!qufno.equals(other.qufno)) {
			return false;
		}
		return true;
	}

}
