package tableVo;

import java.io.Serializable;
import java.util.Date;

/**
 * 질문게시판 댓글 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QnaReply implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 댓글 번호. */
	private Integer qurno;

	/** 댓글 내용. */
	private String qurcontent;

	/** 댓글 작성일. */
	private Date qurdate;

	/** 회원정보. */
	private Member member;

	/** 질문게시판. */
	private Qna qna;

	/**
	 * 생성자.
	 */
	public QnaReply() {
	}

	/**
	 * 댓글 번호을 설정합니다..
	 * 
	 * @param qurno
	 *            댓글 번호
	 */
	public void setQurno(Integer qurno) {
		this.qurno = qurno;
	}

	/**
	 * 댓글 번호을 가져옵니다..
	 * 
	 * @return 댓글 번호
	 */
	public Integer getQurno() {
		return this.qurno;
	}

	/**
	 * 댓글 내용을 설정합니다..
	 * 
	 * @param qurcontent
	 *            댓글 내용
	 */
	public void setQurcontent(String qurcontent) {
		this.qurcontent = qurcontent;
	}

	/**
	 * 댓글 내용을 가져옵니다..
	 * 
	 * @return 댓글 내용
	 */
	public String getQurcontent() {
		return this.qurcontent;
	}

	/**
	 * 댓글 작성일을 설정합니다..
	 * 
	 * @param qurdate
	 *            댓글 작성일
	 */
	public void setQurdate(Date qurdate) {
		this.qurdate = qurdate;
	}

	/**
	 * 댓글 작성일을 가져옵니다..
	 * 
	 * @return 댓글 작성일
	 */
	public Date getQurdate() {
		return this.qurdate;
	}

	/**
	 * 회원정보을 설정합니다..
	 * 
	 * @param member
	 *            회원정보
	 */
	public void setMember(Member member) {
		this.member = member;
	}

	/**
	 * 회원정보을 가져옵니다..
	 * 
	 * @return 회원정보
	 */
	public Member getMember() {
		return this.member;
	}

	/**
	 * 질문게시판을 설정합니다..
	 * 
	 * @param qna
	 *            질문게시판
	 */
	public void setQna(Qna qna) {
		this.qna = qna;
	}

	/**
	 * 질문게시판을 가져옵니다..
	 * 
	 * @return 질문게시판
	 */
	public Qna getQna() {
		return this.qna;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((qurno == null) ? 0 : qurno.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		QnaReply other = (QnaReply) obj;
		if (qurno == null) {
			if (other.qurno != null) {
				return false;
			}
		} else if (!qurno.equals(other.qurno)) {
			return false;
		}
		return true;
	}

}
